### 开启日志
POST http://localhost:17778/api/logging/toggle?enabled=true

### 关闭日志
POST http://localhost:17778/api/logging/toggle?enabled=false

### 查询状态
GET http://localhost:17778/api/logging/status

### 保存 Trace 数据到文件
POST http://localhost:17777/io/traceSave
Content-Type: application/json

{
  "requestId": 123456789,
  "type": "traceSave",
  "binPath": "D://trace-mysql//bin//",
  "tData": {
    "id": 768962893423,
    "path": "E:/trace-dump/backup_task_8"
  }
}

### 加载 Trace 数据从文件
POST http://localhost:17777/io/traceLoad
Content-Type: application/json

{
  "requestId": 123456790,
  "type": "traceLoad",
  "binPath": "D://trace-mysql//bin//",
  "tData": {
    "id": 768962893423,
    "path": "E:/trace-dump/backup_task_8"
  }
}

### 查询任务进度
GET http://localhost:17777/io/task/status/test-task-id

### 清除任务状态
DELETE http://localhost:17777/io/task/clear/test-task-id

### 获取所有任务状态
GET http://localhost:17777/io/task/all
